# Generated by Django 5.0.4 on 2025-10-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("New_Vision", "0002_instructor_course_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="No description available", max_length=300),
        ),
        migrations.AddField(
            model_name="course",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="phone",
            field=models.CharField(default="N/A", max_length=15),
        ),
        migrations.AddField(
            model_name="instructor",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/"),
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="New_Vision.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(default="N/A", max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
