# Generated by Django 5.0.4 on 2025-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "New_Vision",
            "0003_course_description_course_picture_instructor_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="course",
            name="picture",
            field=models.ImageField(default="", upload_to="courses/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instructor",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="picture",
            field=models.ImageField(upload_to="instructors/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="picture",
            field=models.ImageField(upload_to="students/"),
        ),
    ]
